---
title: "11_Quartile_Columns"
author: "Miguel Angel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---

```{r}
library(Hmisc)

#Load the enviroment
#load("C:/BIG FILES/Phenotyping/HemodynamicProjectsDatasetFeb18.RData")

```

# Quartiles per variable

```{r}
Q_total_pressors_formula_mg<-summary(FinalHemodynamicsDataset$total_pressors_formula_mg)
Q_AUT50MAP_total_min<-summary(FinalHemodynamicsDataset$AUT50MAP_total_min)
Q_AWI51_60MAP_total_min<-summary(FinalHemodynamicsDataset$AWI51_60MAP_total_min)
Q_AWI61_65MAP_total_min<-summary(FinalHemodynamicsDataset$AWI61_65MAP_total_min)
Q_AOT65MAP_total_min<-summary(FinalHemodynamicsDataset$AOT65MAP_total_min)
Q_AUT65MAP_total_min<-summary(FinalHemodynamicsDataset$AUT65MAP_total_min)
Q_AUT80SBP_total_min<-summary(FinalHemodynamicsDataset$AUT80SBP_total_min)
Q_AOT80SBP_total_min<-summary(FinalHemodynamicsDataset$AOT80SBP_total_min)
Q_AUT50MAP_total_ratio<-summary(FinalHemodynamicsDataset$AUT50MAP_total_ratio)
Q_AUT65MAP_total_ratio<-summary(FinalHemodynamicsDataset$AUT65MAP_total_ratio)
Q_AUC65MAP_total_mmHgmin<-summary(FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin)
Q_AOC65MAP_total_mmHgmin<-summary(FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin)
Q_TWA65MAP_total_mmHg<-summary(FinalHemodynamicsDataset$TWA65MAP_total_mmHg)
```

## Comparing range to clasify each case's column in a Q

```{r}
#nested if else function

i <- function(if_stat, then) {
  if_stat <- lazyeval::expr_text(if_stat)
  then    <- lazyeval::expr_text(then)
  sprintf("ifelse(%s, %s, ", if_stat, then)
}

e <- function(else_ret) {
  else_ret <- lazyeval::expr_text(else_ret)
  else_ret
}

ie <- function(...) {
  args <- list(...)
  
  for (i in 1:(length(args) - 1) ) {
      if (substr(args[[i]], 1, 6) != "ifelse") {
        stop("All but the last argument, need to be i functions.", call. = FALSE)
      }
  }
  if (substr(args[[length(args)]], 1, 6) == "ifelse"){
    stop("Last argument needs to be an e function.", call. = FALSE)
  }
  args$final <- paste(rep(')', length(args) - 1), collapse = '')
  eval_string <- do.call('paste', args)
  eval(parse(text = eval_string))
}


FinalHemodynamicsDataset['Q_AUC65MAP_total_mmHgmin']<-NA

FinalHemodynamicsDataset$Q_AUC65MAP_total_mmHgmin <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin),NA),
    i(FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin <=  Q_AUC65MAP_total_mmHgmin[2],1),
    i(FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin > Q_AUC65MAP_total_mmHgmin[2] & FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin <= Q_AUC65MAP_total_mmHgmin[3],2),
    i(FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin > Q_AUC65MAP_total_mmHgmin[3] &FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin <= Q_AUC65MAP_total_mmHgmin[5],3),
    i(FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin >=  Q_AUC65MAP_total_mmHgmin[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AOC65MAP_total_mmHgmin']<-NA

FinalHemodynamicsDataset$Q_AOC65MAP_total_mmHgmin <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin),NA),
    i(FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin <=  Q_AOC65MAP_total_mmHgmin[2],1),
    i(FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin > Q_AOC65MAP_total_mmHgmin[2] & FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin <= Q_AOC65MAP_total_mmHgmin[3],2),
    i(FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin > Q_AOC65MAP_total_mmHgmin[3] &FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin <= Q_AOC65MAP_total_mmHgmin[5],3),
    i(FinalHemodynamicsDataset$AOC65MAP_total_mmHgmin >=  Q_AOC65MAP_total_mmHgmin[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_TWA65MAP_total_mmHg']<-NA

FinalHemodynamicsDataset$Q_TWA65MAP_total_mmHg <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$TWA65MAP_total_mmHg),NA),
    i(FinalHemodynamicsDataset$TWA65MAP_total_mmHg <=  Q_TWA65MAP_total_mmHg[2],1),
    i(FinalHemodynamicsDataset$TWA65MAP_total_mmHg > Q_TWA65MAP_total_mmHg[2] & FinalHemodynamicsDataset$TWA65MAP_total_mmHg <= Q_TWA65MAP_total_mmHg[3],2),
    i(FinalHemodynamicsDataset$TWA65MAP_total_mmHg > Q_TWA65MAP_total_mmHg[3] &FinalHemodynamicsDataset$TWA65MAP_total_mmHg <= Q_TWA65MAP_total_mmHg[5],3),
    i(FinalHemodynamicsDataset$TWA65MAP_total_mmHg >=  Q_TWA65MAP_total_mmHg[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_total_pressors_formula_mg']<-NA

FinalHemodynamicsDataset$Q_total_pressors_formula_mg <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$total_pressors_formula_mg),NA),
    i(FinalHemodynamicsDataset$total_pressors_formula_mg <=  Q_total_pressors_formula_mg[2],1),
    i(FinalHemodynamicsDataset$total_pressors_formula_mg > Q_total_pressors_formula_mg[2] & FinalHemodynamicsDataset$total_pressors_formula_mg <= Q_total_pressors_formula_mg[3],2),
    i(FinalHemodynamicsDataset$total_pressors_formula_mg > Q_total_pressors_formula_mg[3] &FinalHemodynamicsDataset$total_pressors_formula_mg <= Q_total_pressors_formula_mg[5],3),
    i(FinalHemodynamicsDataset$total_pressors_formula_mg >=  Q_total_pressors_formula_mg[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AUT50MAP_total_min']<-NA

FinalHemodynamicsDataset$Q_AUT50MAP_total_min <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AUT50MAP_total_min),NA),
    i(FinalHemodynamicsDataset$AUT50MAP_total_min <=  Q_AUT50MAP_total_min[2],1),
    i(FinalHemodynamicsDataset$AUT50MAP_total_min > Q_AUT50MAP_total_min[2] & FinalHemodynamicsDataset$AUT50MAP_total_min <= Q_AUT50MAP_total_min[3],2),
    i(FinalHemodynamicsDataset$AUT50MAP_total_min> Q_AUT50MAP_total_min[3] &FinalHemodynamicsDataset$AUT50MAP_total_min <= Q_AUT50MAP_total_min[5],3),
    i(FinalHemodynamicsDataset$AUT50MAP_total_min >=  Q_AUT50MAP_total_min[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AUT50MAP_total_ratio']<-NA

FinalHemodynamicsDataset$Q_AUT50MAP_total_ratio <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AUT50MAP_total_ratio),NA),
    i(FinalHemodynamicsDataset$AUT50MAP_total_ratio <=  Q_AUT50MAP_total_ratio[2],1),
    i(FinalHemodynamicsDataset$AUT50MAP_total_ratio > Q_AUT50MAP_total_ratio[2] & FinalHemodynamicsDataset$AUT50MAP_total_ratio <= Q_AUT50MAP_total_ratio[3],2),
    i(FinalHemodynamicsDataset$AUT50MAP_total_ratio> Q_AUT50MAP_total_ratio[3] &FinalHemodynamicsDataset$AUT50MAP_total_ratio <= Q_AUT50MAP_total_ratio[5],3),
    i(FinalHemodynamicsDataset$AUT50MAP_total_ratio >=  Q_AUT50MAP_total_ratio[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AWI51_60MAP_total_min']<-NA

FinalHemodynamicsDataset$Q_AWI51_60MAP_total_min <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AWI51_60MAP_total_min),NA),
    i(FinalHemodynamicsDataset$AWI51_60MAP_total_min <=  Q_AWI51_60MAP_total_min[2],1),
    i(FinalHemodynamicsDataset$AWI51_60MAP_total_min > Q_AWI51_60MAP_total_min[2] & FinalHemodynamicsDataset$AWI51_60MAP_total_min <= Q_AWI51_60MAP_total_min[3],2),
    i(FinalHemodynamicsDataset$AWI51_60MAP_total_min> Q_AWI51_60MAP_total_min[3] &FinalHemodynamicsDataset$AWI51_60MAP_total_min <= Q_AWI51_60MAP_total_min[5],3),
    i(FinalHemodynamicsDataset$AWI51_60MAP_total_min >=  Q_AWI51_60MAP_total_min[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AWI61_65MAP_total_min']<-NA

FinalHemodynamicsDataset$Q_AWI61_65MAP_total_min <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AWI61_65MAP_total_min),NA),
    i(FinalHemodynamicsDataset$AWI61_65MAP_total_min <=  Q_AWI61_65MAP_total_min[2],1),
    i(FinalHemodynamicsDataset$AWI61_65MAP_total_min > Q_AWI61_65MAP_total_min[2] & FinalHemodynamicsDataset$AWI61_65MAP_total_min <= Q_AWI61_65MAP_total_min[3],2),
    i(FinalHemodynamicsDataset$AWI61_65MAP_total_min> Q_AWI61_65MAP_total_min[3] &FinalHemodynamicsDataset$AWI61_65MAP_total_min <= Q_AWI61_65MAP_total_min[5],3),
    i(FinalHemodynamicsDataset$AWI61_65MAP_total_min >=  Q_AWI61_65MAP_total_min[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AOT65MAP_total_min']<-NA

FinalHemodynamicsDataset$Q_AOT65MAP_total_min <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AOT65MAP_total_min),NA),
    i(FinalHemodynamicsDataset$AOT65MAP_total_min <=  Q_AOT65MAP_total_min[2],1),
    i(FinalHemodynamicsDataset$AOT65MAP_total_min > Q_AOT65MAP_total_min[2] & FinalHemodynamicsDataset$AOT65MAP_total_min <= Q_AOT65MAP_total_min[3],2),
    i(FinalHemodynamicsDataset$AOT65MAP_total_min> Q_AOT65MAP_total_min[3] &FinalHemodynamicsDataset$AOT65MAP_total_min <= Q_AOT65MAP_total_min[5],3),
    i(FinalHemodynamicsDataset$AOT65MAP_total_min >=  Q_AOT65MAP_total_min[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AUT65MAP_total_min']<-NA

FinalHemodynamicsDataset$Q_AUT65MAP_total_min <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AUT65MAP_total_min),NA),
    i(FinalHemodynamicsDataset$AUT65MAP_total_min <=  Q_AUT65MAP_total_min[2],1),
    i(FinalHemodynamicsDataset$AUT65MAP_total_min > Q_AUT65MAP_total_min[2] & FinalHemodynamicsDataset$AUT65MAP_total_min <= Q_AUT65MAP_total_min[3],2),
    i(FinalHemodynamicsDataset$AUT65MAP_total_min> Q_AUT65MAP_total_min[3] &FinalHemodynamicsDataset$AUT65MAP_total_min <= Q_AUT65MAP_total_min[5],3),
    i(FinalHemodynamicsDataset$AUT65MAP_total_min >=  Q_AUT65MAP_total_min[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AUT65MAP_total_ratio']<-NA

FinalHemodynamicsDataset$Q_AUT65MAP_total_ratio <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AUT65MAP_total_ratio),NA),
    i(FinalHemodynamicsDataset$AUT65MAP_total_ratio <=  Q_AUT65MAP_total_ratio[2],1),
    i(FinalHemodynamicsDataset$AUT65MAP_total_ratio > Q_AUT65MAP_total_ratio[2] & FinalHemodynamicsDataset$AUT65MAP_total_ratio <= Q_AUT65MAP_total_ratio[3],2),
    i(FinalHemodynamicsDataset$AUT65MAP_total_ratio> Q_AUT65MAP_total_ratio[3] &FinalHemodynamicsDataset$AUT65MAP_total_ratio <= Q_AUT65MAP_total_ratio[5],3),
    i(FinalHemodynamicsDataset$AUT65MAP_total_ratio >=  Q_AUT65MAP_total_ratio[5],4),
    e(NA)
  )

FinalHemodynamicsDataset['Q_AUT80SBP_total_min']<-NA

FinalHemodynamicsDataset$Q_AUT80SBP_total_min <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AUT80SBP_total_min),NA),
    i(FinalHemodynamicsDataset$AUT80SBP_total_min <=  Q_AUT80SBP_total_min[2],1),
    i(FinalHemodynamicsDataset$AUT80SBP_total_min > Q_AUT80SBP_total_min[2] & FinalHemodynamicsDataset$AUT80SBP_total_min <= Q_AUT80SBP_total_min[3],2),
    i(FinalHemodynamicsDataset$AUT80SBP_total_min> Q_AUT80SBP_total_min[3] &FinalHemodynamicsDataset$AUT80SBP_total_min <= Q_AUT80SBP_total_min[5],3),
    i(FinalHemodynamicsDataset$AUT80SBP_total_min >=  Q_AUT80SBP_total_min[5],4),
    e(NA)
  )


FinalHemodynamicsDataset['Q_AOT80SBP_total_min']<-NA

FinalHemodynamicsDataset$Q_AOT80SBP_total_min <- 
  ie(
    i(is.na(FinalHemodynamicsDataset$AOT80SBP_total_min),NA),
    i(FinalHemodynamicsDataset$AOT80SBP_total_min <=  Q_AOT80SBP_total_min[2],1),
    i(FinalHemodynamicsDataset$AOT80SBP_total_min > Q_AOT80SBP_total_min[2] & FinalHemodynamicsDataset$AOT80SBP_total_min <= Q_AOT80SBP_total_min[3],2),
    i(FinalHemodynamicsDataset$AOT80SBP_total_min> Q_AOT80SBP_total_min[3] &FinalHemodynamicsDataset$AOT80SBP_total_min <= Q_AOT80SBP_total_min[5],3),
    i(FinalHemodynamicsDataset$AOT80SBP_total_min >=  Q_AOT80SBP_total_min[5],4),
    e(NA)
  )


```


# Tertiles

```{r}
FinalHemodynamicsDataset['T_AUT50MAP_total_min']<-as.numeric(cut2(FinalHemodynamicsDataset$AUT50MAP_total_min, g=3))
FinalHemodynamicsDataset['T_AUT65MAP_total_min']<-as.numeric(cut2(FinalHemodynamicsDataset$AUT65MAP_total_min, g=3))
FinalHemodynamicsDataset['T_AOT65MAP_total_min']<-as.numeric(cut2(FinalHemodynamicsDataset$AOT65MAP_total_min, g=3))
FinalHemodynamicsDataset['T_total_pressors_formula_mg']<-as.numeric(cut2(FinalHemodynamicsDataset$total_pressors_formula_mg, g=3))
FinalHemodynamicsDataset['T_STS_RiskAlgorithm_median_imp']<-as.factor(as.numeric(cut2(FinalHemodynamicsDataset$STS_RiskAlgorithm_median_imp, g=3)))

```


# Creating Deciles Columns
```{r}
library(StatMeasures)
#decileScores <- 
FinalHemodynamicsDataset['D_AUT50MAP_total_min']<-decile(FinalHemodynamicsDataset$AUT50MAP_total_min)
FinalHemodynamicsDataset['D_AWI51_60MAP_total_min']<-decile(FinalHemodynamicsDataset$AWI51_60MAP_total_min)
FinalHemodynamicsDataset['D_AWI61_65MAP_total_min']<-decile(FinalHemodynamicsDataset$AWI61_65MAP_total_min)
FinalHemodynamicsDataset['D_AOT65MAP_total_min']<-decile(FinalHemodynamicsDataset$AOT65MAP_total_min)
FinalHemodynamicsDataset['D_total_pressors_formula_mg']<-decile(FinalHemodynamicsDataset$total_pressors_formula_mg)

```

# Export dataset

```{r eval=FALSE, include=FALSE}
write.csv(FinalHemodynamicsDataset,'FinalHemodynamicsDataset.csv')
```

# Exploring DataSet

```{r eval=FALSE, include=FALSE}
library(summarytools)
view(dfSummary(FinalHemodynamicsDataset))

```
## Cut off points

### Pressors

```{r}
library(dplyr)

FinalHemodynamicsDataset %>% 
  dplyr::group_by(Q_total_pressors_formula_mg)%>%
  dplyr::summarize(min = round(min(total_pressors_formula_mg),2), 
            max = round(max(total_pressors_formula_mg),2)
            
            )
```

### Blood Pressure

```{r}
 
library(dplyr)

FinalHemodynamicsDataset %>% 
  dplyr::group_by(Q_AUC65MAP_total_mmHgmin)%>%
  dplyr::summarize(min = round(min(AUC65MAP_total_mmHgmin), 2),
            max = round(max(AUC65MAP_total_mmHgmin), 2)
            )
```

```{r}
 
library(dplyr)

FinalHemodynamicsDataset %>% 
  dplyr::group_by(Q_AOC65MAP_total_mmHgmin)%>%
  dplyr::summarize(min = round(min(AOC65MAP_total_mmHgmin), 2),
            max = round(max(AOC65MAP_total_mmHgmin), 2)
            )
```


```{r}
library(dplyr)

FinalHemodynamicsDataset %>% 
  dplyr::group_by(Q_TWA65MAP_total_mmHg)%>%
  dplyr::summarize(min = round(min(TWA65MAP_total_mmHg), 2),
            max = round(max(TWA65MAP_total_mmHg), 2)
            )
```

## STS Risk Score

```{r}
library(dplyr)

FinalHemodynamicsDataset %>% 
  dplyr::group_by(T_STS_RiskAlgorithm_median_imp)%>%
  dplyr::summarize(min = round(min(STS_RiskAlgorithm_median_imp), 2),
            max = round(max(STS_RiskAlgorithm_median_imp), 2)
            )
```

# Input Output Data

```{r}
FinalHemodynamicsDataset<-left_join(FinalHemodynamicsDataset, IO_data)
```

# Ejection Fraction Data

```{r}
FinalHemodynamicsDataset<-left_join(FinalHemodynamicsDataset,Ejection_Fraction)
```



# Data Summary

```{r}
library(summarytools)
# select only desired columns to be reviewd
#view(dfSummary(FinalHemodynamicsDataset[,c('AUC65MAP_total_mmHgmin','TWA65MAP_total_mmHg')]))
write.csv(FinalHemodynamicsDataset,'FinalHemodynamicsDataset.csv')
```


