---
title: "Quantiles"
author: "Miguel Ángel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---

# Libs

```{r}
library(dplyr)
library(plotly)
#library(corrplot)
library(Hmisc)
#library(officer)
library(xlsx)
```



```{r setup, include=FALSE}
#load the data
#load("C:/BIG FILES/Phenotyping/HemodynamicProjectsDatasetFeb18.RData")
```


# Plots

## Wrangling the dataset for plotting

```{r eval=FALSE, include=FALSE}
###IMPORTANT detach plyr!!
#detach('package:plyr')


#Tertiles

T_AUT50MAP_total_min_pressors_MAE<-FinalHemodynamicsDataset %>%
dplyr::group_by(T_AUT50MAP_total_min, T_total_pressors_formula_mg)%>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518)
T_AUT50MAP_total_min_pressors_MAE<-T_AUT50MAP_total_min_pressors_MAE[complete.cases(T_AUT50MAP_total_min_pressors_MAE), ]
library(reshape)
T_AUT50MAP_total_min_pressors_MAE_matrix<-cast(data=T_AUT50MAP_total_min_pressors_MAE
     ,T_AUT50MAP_total_min ~ T_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
T_AUT50MAP_total_min_pressors_MAE_matrix<-as.matrix(T_AUT50MAP_total_min_pressors_MAE_matrix)



T_AUT65MAP_total_min_pressors_MAE<-FinalHemodynamicsDataset %>%
dplyr::group_by(T_AUT65MAP_total_min, T_total_pressors_formula_mg) %>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518)
T_AUT65MAP_total_min_pressors_MAE<-T_AUT65MAP_total_min_pressors_MAE[complete.cases(T_AUT65MAP_total_min_pressors_MAE), ]
library(reshape)
T_AUT65MAP_total_min_pressors_MAE_matrix<-cast(data=T_AUT65MAP_total_min_pressors_MAE
     ,T_AUT65MAP_total_min ~ T_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
T_AUT65MAP_total_min_pressors_MAE_matrix<-as.matrix(T_AUT65MAP_total_min_pressors_MAE_matrix)




T_AOT65MAP_total_min_pressors_MAE<-(FinalHemodynamicsDataset) %>%
dplyr::group_by(T_AOT65MAP_total_min, T_total_pressors_formula_mg) %>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518)
T_AOT65MAP_total_min_pressors_MAE<-T_AOT65MAP_total_min_pressors_MAE[complete.cases(T_AOT65MAP_total_min_pressors_MAE), ]

#Quartiles

Q_AUT50MAP_total_min_pressors_MAE<-FinalHemodynamicsDataset %>%
dplyr::group_by(Q_AUT50MAP_total_min, Q_total_pressors_formula_mg)%>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518*100)
Q_AUT50MAP_total_min_pressors_MAE<-Q_AUT50MAP_total_min_pressors_MAE[complete.cases(Q_AUT50MAP_total_min_pressors_MAE), ]
library(reshape)
Q_AUT50MAP_total_min_pressors_MAE_matrix<-cast(data=Q_AUT50MAP_total_min_pressors_MAE
     ,Q_AUT50MAP_total_min ~ Q_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
Q_AUT50MAP_total_min_pressors_MAE_matrix<-as.data.frame(Q_AUT50MAP_total_min_pressors_MAE_matrix)
colnames(Q_AUT50MAP_total_min_pressors_MAE_matrix)<-c('','total pressors Q1','total pressors Q2','total pressors Q3','total pressors Q4')
rownames(Q_AUT50MAP_total_min_pressors_MAE_matrix)<-c('total AUT50 MAP  Q1','total AUT50 MAP  Q2','total AUT50 MAP  Q3','total AUT50 MAP  Q4')
Q_AUT50MAP_total_min_pressors_MAE_matrix[,1]<-NULL
Q_AUT50MAP_total_min_pressors_MAE_matrix<-round(Q_AUT50MAP_total_min_pressors_MAE_matrix,2)

Q_AUT65MAP_total_min_pressors_MAE<-FinalHemodynamicsDataset%>%
dplyr::group_by(Q_AUT65MAP_total_min, Q_total_pressors_formula_mg) %>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518*100)
Q_AUT65MAP_total_min_pressors_MAE<-Q_AUT65MAP_total_min_pressors_MAE[complete.cases(Q_AUT65MAP_total_min_pressors_MAE), ]
library(reshape)
Q_AUT65MAP_total_min_pressors_MAE_matrix<-cast(data=Q_AUT65MAP_total_min_pressors_MAE
     ,Q_AUT65MAP_total_min ~ Q_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
Q_AUT65MAP_total_min_pressors_MAE_matrix<-as.data.frame(Q_AUT65MAP_total_min_pressors_MAE_matrix)
colnames(Q_AUT65MAP_total_min_pressors_MAE_matrix)<-c('','total pressors Q1','total pressors Q2','total pressors Q3','total pressors Q4')
rownames(Q_AUT65MAP_total_min_pressors_MAE_matrix)<-c('total AUT65 MAP  Q1','total AUT65 MAP  Q2','total AUT65 MAP  Q3','total AUT65 MAP  Q4')
Q_AUT65MAP_total_min_pressors_MAE_matrix[,1]<-NULL
Q_AUT65MAP_total_min_pressors_MAE_matrix<-round(Q_AUT65MAP_total_min_pressors_MAE_matrix,2)


Q_AOT65MAP_total_min_pressors_MAE<-(FinalHemodynamicsDataset) %>%
dplyr::group_by(Q_AOT65MAP_total_min, Q_total_pressors_formula_mg) %>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518*100)
Q_AOT65MAP_total_min_pressors_MAE<-Q_AOT65MAP_total_min_pressors_MAE[complete.cases(Q_AOT65MAP_total_min_pressors_MAE), ]
library(reshape)
Q_AOT65MAP_total_min_pressors_MAE_matrix<-cast(data=Q_AOT65MAP_total_min_pressors_MAE
     ,Q_AOT65MAP_total_min ~ Q_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
Q_AOT65MAP_total_min_pressors_MAE_matrix<-as.data.frame(Q_AOT65MAP_total_min_pressors_MAE_matrix)
colnames(Q_AOT65MAP_total_min_pressors_MAE_matrix)<-c('','total pressors Q1','total pressors Q2','total pressors Q3','total pressors Q4')
rownames(Q_AOT65MAP_total_min_pressors_MAE_matrix)<-c('total AOT65 MAP  Q1','total AOT65 MAP  Q2','total AOT65 MAP  Q3','total AOT65 MAP  Q4')
Q_AOT65MAP_total_min_pressors_MAE_matrix[,1]<-NULL
Q_AOT65MAP_total_min_pressors_MAE_matrix<-round(Q_AOT65MAP_total_min_pressors_MAE_matrix,2)

#Quartiles of ratio

Q_AUT50MAP_total_ratio_pressors_MAE<-FinalHemodynamicsDataset %>%
dplyr::group_by(Q_AUT50MAP_total_ratio, Q_total_pressors_formula_mg)%>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518*100)
Q_AUT50MAP_total_ratio_pressors_MAE<-Q_AUT50MAP_total_ratio_pressors_MAE[complete.cases(Q_AUT50MAP_total_ratio_pressors_MAE), ]
library(reshape)
Q_AUT50MAP_total_ratio_pressors_MAE_matrix<-cast(data=Q_AUT50MAP_total_ratio_pressors_MAE
     ,Q_AUT50MAP_total_ratio ~ Q_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
Q_AUT50MAP_total_ratio_pressors_MAE_matrix<-as.data.frame(Q_AUT50MAP_total_ratio_pressors_MAE_matrix)
colnames(Q_AUT50MAP_total_ratio_pressors_MAE_matrix)<-c('','total pressors Q1','total pressors Q2','total pressors Q3','total pressors Q4')
rownames(Q_AUT50MAP_total_ratio_pressors_MAE_matrix)<-c('ratio AUT50 MAP  Q1','ratio AUT50 MAP  Q2','ratio AUT50 MAP  Q3','ratio AUT50 MAP  Q4')
Q_AUT50MAP_total_ratio_pressors_MAE_matrix[,1]<-NULL
Q_AUT50MAP_total_ratio_pressors_MAE_matrix<-round(Q_AUT50MAP_total_ratio_pressors_MAE_matrix,2)



Q_AUT65MAP_total_ratio_pressors_MAE<-FinalHemodynamicsDataset%>%
dplyr::group_by(Q_AUT65MAP_total_ratio, Q_total_pressors_formula_mg) %>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518*100)
Q_AUT65MAP_total_ratio_pressors_MAE<-Q_AUT65MAP_total_ratio_pressors_MAE[complete.cases(Q_AUT65MAP_total_ratio_pressors_MAE), ]
library(reshape)
Q_AUT65MAP_total_ratio_pressors_MAE_matrix<-cast(data=Q_AUT65MAP_total_ratio_pressors_MAE
     ,Q_AUT65MAP_total_ratio ~ Q_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
Q_AUT65MAP_total_ratio_pressors_MAE_matrix<-as.data.frame(Q_AUT65MAP_total_ratio_pressors_MAE_matrix)
colnames(Q_AUT65MAP_total_ratio_pressors_MAE_matrix)<-c('','total pressors Q1','total pressors Q2','total pressors Q3','total pressors Q4')
rownames(Q_AUT65MAP_total_ratio_pressors_MAE_matrix)<-c('ratio AUT65 MAP  Q1','ratio AUT65 MAP  Q2','ratio AUT65 MAP  Q3','ratio AUT65 MAP  Q4')
Q_AUT65MAP_total_ratio_pressors_MAE_matrix[,1]<-NULL
Q_AUT65MAP_total_ratio_pressors_MAE_matrix<-round(Q_AUT65MAP_total_ratio_pressors_MAE_matrix,2)


# AUC Quartiles 


Q_AUC65MAP_total_mmHgmin_pressors_MAE<-FinalHemodynamicsDataset%>%
dplyr::group_by(Q_AUC65MAP_total_mmHgmin, Q_total_pressors_formula_mg) %>%
dplyr::summarise('MAE rate (%)'=sum(Any_MAE)/518*100)
Q_AUC65MAP_total_mmHgmin_pressors_MAE<-Q_AUC65MAP_total_mmHgmin_pressors_MAE[complete.cases(Q_AUC65MAP_total_mmHgmin_pressors_MAE), ]
library(reshape)
Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix<-cast(data=Q_AUC65MAP_total_mmHgmin_pressors_MAE
     ,Q_AUC65MAP_total_mmHgmin ~ Q_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix<-as.data.frame(Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix)
colnames(Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix)<-c('','total pressors Q1','total pressors Q2','total pressors Q3','total pressors Q4')
rownames(Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix)<-c('total AUC65 MAP  Q1','total AUC65 MAP  Q2','total AUC65 MAP  Q3','total AUC65 MAP  Q4')
Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix[,1]<-NULL
Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix<-round(Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix,2)

# TWA Quartiles 


Q_TWA65MAP_total_mmHg_pressors_MAE<-FinalHemodynamicsDataset%>%
dplyr::group_by(Q_TWA65MAP_total_mmHg, Q_total_pressors_formula_mg) %>%
dplyr::summarise(total_patientswith_MAE=sum(Any_MAE)/518*100)
Q_TWA65MAP_total_mmHg_pressors_MAE<-Q_TWA65MAP_total_mmHg_pressors_MAE[complete.cases(Q_TWA65MAP_total_mmHg_pressors_MAE), ]
library(reshape)
Q_TWA65MAP_total_mmHg_pressors_MAE_matrix<-cast(data=Q_TWA65MAP_total_mmHg_pressors_MAE
     ,Q_TWA65MAP_total_mmHg ~ Q_total_pressors_formula_mg
     ,value = 'total_patientswith_MAE')
Q_TWA65MAP_total_mmHg_pressors_MAE_matrix<-as.data.frame(Q_TWA65MAP_total_mmHg_pressors_MAE_matrix)
colnames(Q_TWA65MAP_total_mmHg_pressors_MAE_matrix)<-c('','total pressors Q1','total pressors Q2','total pressors Q3','total pressors Q4')
rownames(Q_TWA65MAP_total_mmHg_pressors_MAE_matrix)<-c('total TWA MAP 65 Q1','total TWA MAP 65 Q2','total TWA MAP 65 Q3','total TWA MAP 65 Q4')
Q_TWA65MAP_total_mmHg_pressors_MAE_matrix[,1]<-NULL
Q_TWA65MAP_total_mmHg_pressors_MAE_matrix<-round(Q_TWA65MAP_total_mmHg_pressors_MAE_matrix,2)

```

# 3D Plots Data

## Exporting to excel

```{r}
write.xlsx(T_AUT50MAP_total_min_pressors_MAE_matrix, "T_AUT50MAP_total_min_pressors_MAE_matrix.xlsx")
write.xlsx(T_AUT65MAP_total_min_pressors_MAE_matrix, "T_AUT65MAP_total_min_pressors_MAE_matrix.xlsx")

write.xlsx(Q_AUT50MAP_total_min_pressors_MAE_matrix, "Q_AUT50MAP_total_min_pressors_MAE_matrix.xlsx")
write.xlsx(Q_AUT65MAP_total_min_pressors_MAE_matrix, "Q_AUT65MAP_total_min_pressors_MAE_matrix.xlsx")
write.xlsx(Q_AOT65MAP_total_min_pressors_MAE_matrix, "Q_AOT65MAP_total_min_pressors_MAE_matrix.xlsx")

#quartiles ratio

write.xlsx(Q_AUT50MAP_total_ratio_pressors_MAE_matrix, "Q_AUT50MAP_total_ratio_pressors_MAE_matrix.xlsx")
write.xlsx(Q_AUT65MAP_total_ratio_pressors_MAE_matrix, "Q_AUT65MAP_total_ratio_pressors_MAE_matrix.xlsx")

# AUC
write.xlsx(Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix,
'Q_AUC65MAP_total_mmHgmin_pressors_MAE_matrix.xlsx')
# TWA 
write.xlsx(Q_TWA65MAP_total_mmHg_pressors_MAE_matrix,
'Q_TWA65MAP_total_mmHg_pressors_MAE_matrix.xlsx')
```


# 3D Tertiles in R

```{r}
library('plot3D')



hist3D( main =  paste("T AUT50MAP Plot\n Number of Cases =", sum(T_AUT50MAP_total_min_pressors_MAE_matrix))
   , x = c(1:3)
   , y = c(1:3)
   , z = T_AUT50MAP_total_min_pressors_MAE_matrix
   , scale = F, expand = 0.01, bty = "b2", phi = 20, col = "#1e8bc3"
   , border = "white", shade = 0.5, ltheta = 90
   , space = 0.3 #space between bars
   , ticktype = "detailed", d = 2
   ,resfac=3 #resolution
   ,xlab='T AUT50MAP total'
   ,ylab='T total pressors'
   ,zlab='patients with Any MAE'
   ,zlim=c(0,170))

hist3D( main =  paste("T AUT65MAP Plot\n Number of Cases =", sum(T_AUT65MAP_total_min_pressors_MAE_matrix))
   , x = c(1:3)
   , y = c(1:3)
   , z = T_AUT65MAP_total_min_pressors_MAE_matrix
   , scale = F, expand = 0.01, bty = "b2", phi = 20, col = "#1e8bc3"
   , border = "white", shade = 0.5, ltheta = 90
   , space = 0.3 #space between bars
   , ticktype = "detailed", d = 2
   ,resfac=3 #resolution
   ,xlab='T AUT65MAP total'
   ,ylab='T total pressors'
   ,zlab='patients with Any MAE'
   ,zlim=c(0,170))

# Make the rgl version
# Animated version
# library("plot3Drgl")
# plotrgl()
```

# 3D Quartiles in R

```{r}
library('plot3D')

hist3D( main =  paste("Q AUT50MAP Plot\n Number of Cases =", sum(Q_AUT50MAP_total_min_pressors_MAE_matrix))
   , x = c(1:4)
   , y = c(1:4)
   , z = Q_AUT50MAP_total_min_pressors_MAE_matrix
   , scale = F, expand = 0.01, bty = "b2", phi = 20, col = "#1e8bc3"
   , border = "white", shade = 0.5, ltheta = 90
   , space = 0.3 #space between bars
   , ticktype = "detailed", d = 2
   ,resfac=3 #resolution
   ,xlab='Q AUT50MAP total'
   ,ylab='Q total pressors'
   ,zlab='patients with Any MAE'
   ,zlim=c(0,170))

hist3D( main =  paste("Q AUT65MAP Plot\n Number of Cases =", sum(Q_AUT65MAP_total_min_pressors_MAE_matrix))
   , x = c(1:4)
   , y = c(1:4)
   , z = Q_AUT65MAP_total_min_pressors_MAE_matrix
   , scale = F, expand = 0.01, bty = "b2", phi = 20, col = "#1e8bc3"
   , border = "white", shade = 0.5, ltheta = 90
   , space = 0.3 #space between bars
   , ticktype = "detailed", d = 2
   ,resfac=3 #resolution
   ,xlab='Q AUT65MAP total'
   ,ylab='Q total pressors'
   ,zlab='patients with Any MAE'
   ,zlim=c(0,170))


```

# 2D Plots

## Quartiles

## Q_AUT50MAP_total_min_pressors_MAE 2D test

### Q_AUT50MAP_total_min

```{r eval=FALSE, include=FALSE}
library(plotly)
library(dplyr)
library(scales)
  
p1<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_total_pressors_formula_mg==1) %>%
  dplyr::group_by(Q_AUT50MAP_total_min) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(  x = ~Q_AUT50MAP_total_min
          , y= ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="OrRd")(9)[5] )
          , name = 'Q1 pressors(mg) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )

p2<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_total_pressors_formula_mg==2) %>%
  dplyr::group_by(Q_AUT50MAP_total_min) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(  x = ~Q_AUT50MAP_total_min
          , y = ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="OrRd")(9)[6] )
          , name = 'Q2 pressors(mg) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )

p3<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_total_pressors_formula_mg==3) %>%
  dplyr::group_by(Q_AUT50MAP_total_min) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(  x = ~Q_AUT50MAP_total_min
          , y = ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="OrRd")(9)[7] )
          , name = 'Q3 pressors(mg) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )

p4<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_total_pressors_formula_mg==4) %>%
  dplyr::group_by(Q_AUT50MAP_total_min) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(  x = ~Q_AUT50MAP_total_min
          , y = ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="OrRd")(9)[8] )
          , name = 'Q4 pressors(mg) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )

library(plotly)
plotly::subplot(p1, p2, p3, p4,nrows = 2,titleY = T,titleX = T,shareX = T,shareY = T) %>% 
   layout(
       title = paste('Total_Patients with Any_MAE: ', sum(Q_AUT50MAP_total_min_pressors_MAE$total_patientswith_MAE))
     )

```


### Q_total_pressors_formula_mg

```{r}
library(plotly)
library(dplyr)
library(scales)
  
p1<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_AUT50MAP_total_min==1) %>%
  dplyr::group_by(Q_total_pressors_formula_mg) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(    x = ~Q_total_pressors_formula_mg
          , y= ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="Blues")(9)[5] )
          , name = 'Q1 AUT50MAP (mins) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )

p2<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_AUT50MAP_total_min==2) %>%
  dplyr::group_by(Q_total_pressors_formula_mg) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(    x = ~Q_total_pressors_formula_mg
          , y = ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="Blues")(9)[6] )
          , name = 'Q2 AUT50MAP (mins) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )

p3<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_AUT50MAP_total_min==3) %>%
  dplyr::group_by(Q_total_pressors_formula_mg) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(    x = ~Q_total_pressors_formula_mg
          , y = ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="Blues")(9)[7] )
          , name = 'Q3 AUT50MAP (mins) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )

p4<-Q_AUT50MAP_total_min_pressors_MAE %>%
  dplyr::filter(Q_AUT50MAP_total_min==4) %>%
  dplyr::group_by(Q_total_pressors_formula_mg) %>%
  dplyr::summarise(total_patientswith_MAE=sum(total_patientswith_MAE)) %>%
  plot_ly(    x = ~Q_total_pressors_formula_mg
          , y = ~total_patientswith_MAE
          , type = 'bar'
          , marker = list(color = brewer_pal(palette="Blues")(9)[8] )
          , name = 'Q4 AUT50MAP (mins) '
          ) %>%layout(  yaxis = list(range = c(0, 170))    )
library(plotly)
pfinal<-plotly::subplot(p1, p2, p3, p4,nrows = 2,titleY = T,titleX = T,shareX = T,shareY = T) %>% 
   layout(
       title = paste('Total_Patients with Any_MAE: ', sum(Q_AUT50MAP_total_min_pressors_MAE$total_patientswith_MAE))
     )

```

# Boxplot for all the bands MAP

```{r}
library(dplyr)
library(plotly)
library(RColorBrewer)
palette <- brewer.pal(9, "Set1")

# annotations
a <- list(
  text = "Mean Arterial Pressure Bands and time in minutes patients spent on that band.",
  font = list(size = 16),
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
)

x <- list( title = "Total time spent in a given threshold (min)" )
p1 <- plot_ly(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==0,]$AUT65MAP_total_min, type = "box",name = "<65 No MAE"
               ,marker = list(color = '#2ecc71'),opacity = 0.8, line = list(color = '#27ae60')) %>%
  add_trace(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==1,]$AUT65MAP_total_min,name = "<65 Any MAE"
               ,marker = list(color = '#e74c3c'),opacity = 0.8, line = list(color = '#c0392b')) %>%  
  
  add_trace(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==0,]$AOT65MAP_total_min,name = ">65 No MAE"
               ,marker = list(color = '#2ecc71'),opacity = 0.8, line = list(color = '#27ae60')) %>%
  add_trace(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==1,]$AOT65MAP_total_min,name = ">65 Any MAE"
               ,marker = list(color = '#e74c3c'),opacity = 0.8, line = list(color = '#c0392b')) %>%

 


  layout(showlegend = F,xaxis = x
         #, yaxis = list(range=c(0,800))
         , annotations = a)  


#htmlwidgets::saveWidget(sp1, "boxplots.html")
```

# Boxplot for threshold <=65

```{r}
library(dplyr)
library(plotly)
library(RColorBrewer)
palette <- brewer.pal(9, "Set1")

# annotations
a <- list(
  text = "MAP < 65 mmHg duration per group",
  font = list(size = 16),
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
)

y <- list( title = "Total duration (min)" )
x <- list( title = "Groups" )
p1 <- plot_ly(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==0,]$AUT65MAP_total_min, type = "box",name = "Absent MAE"
               ,marker = list(color = '#2ecc71'),opacity = 0.8, line = list(color = '#27ae60')) %>%
  add_trace(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==1,]$AUT65MAP_total_min,name = "Present MAE"
               ,marker = list(color = '#e74c3c'),opacity = 0.8, line = list(color = '#c0392b')) %>%  
  
  add_trace(y = FinalHemodynamicsDataset$AUT65MAP_total_min,name = "All patients"
               ,marker = list(color = '#2980b9'),opacity = 0.8, line = list(color = '#2980b9')) %>%    

  layout(showlegend = F
         , xaxis = x
         , yaxis = y
         , annotations = a)  

a <- list(
  text = "AUC MAP < 65 mmHg",
  font = list(size = 16),
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
)

y <- list( title = "Area under the curve (mmHg•min)" )
x <- list( title = "Groups" )
p2 <- plot_ly(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==0,]$AUC65MAP_total_mmHgmin, type = "box",name = "Absent MAE"
               ,marker = list(color = '#2ecc71'),opacity = 0.8, line = list(color = '#27ae60')) %>%
  add_trace(y = FinalHemodynamicsDataset[FinalHemodynamicsDataset$Any_MAE==1,]$AUC65MAP_total_mmHgmin,name = "Present MAE"
               ,marker = list(color = '#e74c3c'),opacity = 0.8, line = list(color = '#c0392b')) %>%  
  
  add_trace(y = FinalHemodynamicsDataset$AUC65MAP_total_mmHgmin,name = "All patients"
               ,marker = list(color = '#2980b9'),opacity = 0.8, line = list(color = '#2980b9')) %>%    

  layout(showlegend = F
         , xaxis = x
         , yaxis = y
         , annotations = a)  

#htmlwidgets::saveWidget(sp1, "boxplots.html")
```


# Correlations

```{r}

sapply(relevant_data_imputed, class)

cor_periods_min<-cor(relevant_data_imputed[,c('Age','duration_Surgery_min','total_pressors_formula_mg','STS_RiskAlgorithm_mean_imp')])

#non interactive circle corplot
cortable<-corrplot(cor_periods_min, method = "circle")

write.xlsx(as.data.frame(print(cortable)), "cortable.xlsx")

```

# Odd Ratio Plots

# General model

```{r}
#Generate plots

df <- oddsratios_table

labels<-c('Age', 'Category: Aortic Surgery', 'Category: CABG + Valve', 'Category: Other', 'Category: Valve', 'Cross Clamp Time' ,'delta HCT pct', 'Gender: Female', 'Mean EF','AUC MAP 65 mmHg Q2', 'AUC MAP 65 mmHg Q3', 'AUC MAP 65 mmHg Q4', 'total pressors formula mg Q2', 'total pressors formula mg Q3', 'total pressors formula mg Q4', 'STS Risk Algorithm Tertile 2', 'STS Risk Algorithm Tertile 3')
number_of_exposures<-length(labels)+1

df <- data.frame(yAxis = 2:number_of_exposures,
                 boxOdds = oddsratios_table$OR[2:number_of_exposures] ,
                 boxCILow = oddsratios_table$`2.5 %`[2:number_of_exposures],  
                 boxCIHigh = oddsratios_table$`97.5 %`[2:number_of_exposures]
)
#df <- df[order(df$boxOdds),]

p<-ggplot(df, aes(x = boxOdds
                  , y = labels
                  )) + 
  geom_vline(aes(xintercept = 1), size = .1, linetype = "dashed") + 
  geom_errorbarh(aes(xmax = boxCIHigh, xmin = boxCILow)
                 , size = .5
                 , height = .2
                 , color = "gray50") +
  geom_point(size = 2, color = "#2980b9") +
  #coord_trans(x = scales:::exp_trans(1.01)) +
  #scale_y_continuous(breaks = c(-1:1),labels = c(-1:1)) +
  theme_bw()+
  theme(panel.grid.minor = element_blank()) +
  ylab("Exposure") +
  xlab("Odds ratio") +
  ggtitle("Impact on Any MAE")

p<-ggplotly(p%>%layout(hovermode = 'compare'))

```

# Exploratory Analysis

```{r}
#Generate plots

df <- oddsratios_table


labels2<-c('Age', 'Category: CABG + Valve', 'Category: Valve', 'delta HCT pct', 'Gender: Female', 'Mean EF','AUC MAP 65 mmHg Q2', 'AUC MAP 65 mmHg Q3', 'AUC MAP 65 mmHg Q4', 'total pressors formula mg Q2', 'total pressors formula mg Q3', 'total pressors formula mg Q4')
number_of_exposures2<-length(labels2)+1


df <- data.frame(yAxis = 2:number_of_exposures2,
                 boxOdds = oddsratios_table$OR[2:number_of_exposures2] ,
                 boxCILow = oddsratios_table$`2.5 %`[2:number_of_exposures2],  
                 boxCIHigh = oddsratios_table$`97.5 %`[2:number_of_exposures2]
)
#df <- df[order(df$boxOdds),]

p<-ggplot(df, aes(x = boxOdds
                  , y = labels2
                  )) + 
  geom_vline(aes(xintercept = 1), size = .1, linetype = "dashed") + 
  geom_errorbarh(aes(xmax = boxCIHigh, xmin = boxCILow)
                 , size = .5
                 , height = .2
                 , color = "gray50") +
  geom_point(size = 2, color = "#2980b9") +
  #coord_trans(x = scales:::exp_trans(1.01)) +
  #scale_y_continuous(breaks = c(-1:1),labels = c(-1:1)) +
  theme_bw()+
  theme(panel.grid.minor = element_blank()) +
  ylab("Exposure") +
  xlab("Odds ratio") +
  ggtitle("Impact on Any MAE")

```

# Bubble plot

```{r}
colnames(Q_TWA65MAP_total_mmHg_pressors_MAE)[3]<-'MAE rate percentage'

p <- plot_ly(Q_TWA65MAP_total_mmHg_pressors_MAE
             , x = ~as.character(Q_TWA65MAP_total_mmHg)
             , y = ~as.character(Q_total_pressors_formula_mg)
             , text = ~round(`MAE rate percentage`,2)
             , textfont = list( size = 10
                                #,color = '#000000'
                                )
             , type = 'scatter'
             , mode = 'markers+text'
             , color = ~`MAE rate percentage`
             , size = ~`MAE rate percentage`
             , colors = c('#f1a9a087','#bd1200')
             , sizes = c(10, 120)
             , showlegend = F
             , marker = list(
               #size =~total_patientswith_MAE
                opacity = 1
          , sizemode = 'diameter')) %>%
  layout(
#title = 'Any MAE rate (%) for TWA-MAP under 65 mmHgNumber of cases = 518',
         xaxis = list(showgrid = T, title='vasopressors dose Q'),
         yaxis = list(showgrid = T, title='TWA-MAP < 65 mmHg Q'))

htmlwidgets::saveWidget(p, "bubbleplot.html")

```



