---
title: "Table1"
author: "Miguel Angel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---


```{r setup, include=FALSE}
#load the data
#load("C:/BIG FILES/Phenotyping/HemodynamicProjectsDatasetFeb18.RData")
```

# Load libs
```{r}
library(tableone)
library(magrittr)
library(officer)
library(xlsx)
library(dplyr)
```

Including fluid data only for table1 (not for modeling)

```{r}
FinalHemodynamicsDataset_for_table1<-FinalHemodynamicsDataset
FinalHemodynamicsDataset_for_table1<-left_join(FinalHemodynamicsDataset_for_table1,IO_data_Fluids_summarized)
```


# Table 1

```{r}
listVars
listVarstab1<-c(listVars,"STS_RiskAlgorithm_median_imp","delta_HCT_pct_median_imp","mean_ef_median_imp","Colloids_ml","Crystalloids_ml","Cross_Clamp_Time","duration_CPB_min","AUT65MAP_CPB_min")


catVars<-c("Gender",
  "Category",
  #Background diseases
  "Diabetes",
  "RFDyslipidemia",
  "Hypertension_final",
  "Smoking",
  "Congestive_Heart_Failure",
  "Previous_myocardial_infarction",
  "ChronicLungDisease",
  "Dialysis",
  #Preoperative medications
  "PreOpMedBetaBlockers",
  "PreOpMedACEI_or_ARBs",
  "PreOpMedInotropes",
  "PreOpMedSteroids",
  "PreOpMedAspirin",
  "PreOpMedLipidLowering") #AKA statins

table1 <- CreateTableOne(vars = listVarstab1, data = FinalHemodynamicsDataset_for_table1, factorVars = catVars,testNormal=oneway.test 
                        #strata is usefull in case we want several columns to stratify by
                         )

table1strat <- CreateTableOne(vars = listVarstab1, data = FinalHemodynamicsDataset_for_table1, factorVars = catVars,testNormal=oneway.test 
                        ,strata = c("Any_MAE")
                        #strata is usefull in case we want several columns to stratify by
                         )
## nonnormal specifies variables to be shown as median [IQR]
# 
# testApprox A function used to perform the large sample approximation based tests. The
# default is chisq.test. This is not recommended when some of the cell have
# small counts like fewer than 5.

# As an aside, the following code may help for your projects, as it improves the presentation of the tables above.  You will still need to update the column and row names manually, but this should paste nicely into Word or LateX!

write.xlsx(as.data.frame(print(table1)), "/Users/marmengol/MEGA/Boston/BIDMC-Harvard/Phenotyping/Tables and Figures/table1.xlsx")
write.xlsx(as.data.frame(print(table1strat)), "/Users/marmengol/MEGA/Boston/BIDMC-Harvard/Phenotyping/Tables and Figures/table1strat.xlsx")


#  if(!("dplyr" %in% installed.packages()[,1])) {
#  install.packages("dplyr")
#  }
# library(dplyr)
# test<-table1 %>% print(
#   printToggle      = FALSE,
#   showAllLevels    = TRUE,
#   cramVars         = "kon"
# ) %>% 
# {data.frame(
#   variable_name             = gsub(" ", "&nbsp;", rownames(.), fixed = TRUE), ., 
#   row.names        = NULL, 
#   check.names      = FALSE, 
#   stringsAsFactors = FALSE)} %>% 
# knitr::kable()

```

# Table 2

```{r}


library(tableone)
library(magrittr)

listExposures<-c('AOT30DBP_postCPB_min','AOT30DBP_preCPB_min','AOT30DBP_total_min','AOT65MAP_CPB_min','AOT65MAP_postCPB_min','AOT65MAP_preCPB_min','AOT65MAP_total_min','AOT95SBP_postCPB_min','AOT95SBP_preCPB_min','AOT95SBP_total_min','AUT30DBP_postCPB_min','AUT30DBP_preCPB_min','AUT30DBP_total_min','AUT50MAP_CPB_min','AUT50MAP_postCPB_min','AUT50MAP_preCPB_min','AUT50MAP_total_min','AUT65MAP_CPB_min','AUT65MAP_postCPB_min','AUT65MAP_preCPB_min','AUT65MAP_total_min','AUT95SBP_postCPB_min','AUT95SBP_preCPB_min','AUT95SBP_total_min','AWI51_60MAP_CPB_min','AWI51_60MAP_postCPB_min','AWI51_60MAP_preCPB_min','AWI51_60MAP_total_min','AWI61_65MAP_CPB_min','AWI61_65MAP_postCPB_min','AWI61_65MAP_preCPB_min','AWI61_65MAP_total_min','duration_CPB_min','duration_postCPB_min','duration_preCPB_min','duration_Surgery_min')

table2all <- CreateTableOne(vars = listExposures, data = FinalHemodynamicsDataset_for_table1, testNormal=oneway.test)

write.xlsx(as.data.frame(print(table2all)), "table2all.xlsx")


table2strat <- CreateTableOne(vars = listExposures, data = FinalHemodynamicsDataset_for_table1, factorVars = listOutstable2,testNormal=oneway.test 
                        ,strata = c("Any_MAE") )
                        
write.xlsx(as.data.frame(print(table2strat)), "table2strat.xlsx")
                        
#strata is usefull in case we want several columns to stratify by
# nonnormal specifies variables to be shown as median [IQR]
# testApprox A function used to perform the large sample approximation based tests. The
# default is chisq.test. This is not recommended when some of the cell have
# small counts like fewer than 5.

```

# Table 3

```{r}


library(tableone)
library(magrittr)

listOutstable2<-c('Any_MAE',listOuts)

table2all <- CreateTableOne(vars = listOutstable2, data = FinalHemodynamicsDataset, factorVars = listOutstable2,testNormal=oneway.test 
                         )

table2strat <- CreateTableOne(vars = listOutstable2, data = FinalHemodynamicsDataset, factorVars = listOutstable2,testNormal=oneway.test 
                        ,strata = c("Any_MAE"))
                        
write.xlsx(as.data.frame(print(table2strat)), "table2strat.xlsx")
                        
                        #strata is usefull in case we want several columns to stratify by
## nonnormal specifies variables to be shown as median [IQR]
# 
# testApprox A function used to perform the large sample approximation based tests. The
# default is chisq.test. This is not recommended when some of the cell have
# small counts like fewer than 5.

# table2<-print(table2,estApprox=listVars, exact = "stage", quote = TRUE,showAllLevels  = TRUE)
# 
# docx( ) %>%
#     addFlexTable(table2 %>%
#     FlexTable(header.cell.props = cellProperties( background.color = "#003366"),
#               header.text.props = textBold( color = "white" ),
#               add.rownames = TRUE ) %>%
#               setZebraStyle( odd = "#DDDDDD", even = "#FFFFFF" ) ) %>%
#     writeDoc(file = "table2.docx")
# 
# browseURL("table2.docx") #wordfile
```

